import { IMessage, IUser } from '@/types';

export const IMAGE_1 =
  'https://instagram.fccu13-2.fna.fbcdn.net/v/t51.2885-19/455795226_846316080785062_4864498626493087599_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.fccu13-2.fna.fbcdn.net&_nc_cat=110&_nc_ohc=cCQreSVzDO8Q7kNvgFOsNYj&_nc_gid=4af29bb5ea73447190f52b7257f13b8c&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_AYAeLc1t3C8P1EYOP_4BkNOkPQP-ndrsj09BUkM17IV6wg&oe=670B205D&_nc_sid=7a9f4b';
export const IMAGE_2 =
  'https://www.pixel4k.com/wp-content/uploads/2021/08/girl-adjusting-hairs-4k_1629241627-1536x864.jpg';
export const WALLPAPER_URI =
  'https://e1.pxfuel.com/desktop-wallpaper/407/713/desktop-wallpaper-in-celebration-of-whatsapps-dark-mode-whatsapp-aesthetic.jpg';

export const SENDER: IUser = {
  fullname: 'Marybeth Tonks',
  phone: '+998-879-396-3329',
  profilePicture: IMAGE_2,
  id: '',
  accoutId: '',
};

export const ME: IUser = {
  fullname: 'Soumo',
  phone: '+917478398178',
  profilePicture: IMAGE_1,
  id: '',
  accoutId: '',
};

export const MESSAGES: IMessage[] = [
  {
    id: '1',
    fileType: 'None',
    text: 'Hello, how are you?',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([
      ['❤️', 2],
      ['😂', 1],
    ]),
    self: true,
    sender: ME,
  },
  {
    id: '2',
    fileType: 'Image',
    text: 'Check this out!',
    timeStamp: new Date(),
    file: 'https://images.pexels.com/photos/18069813/pexels-photo-18069813/free-photo-of-an-artist-s-illustration-of-artificial-intelligence-ai-this-piece-explores-the-prediction-method-used-in-large-language-models-it-was-created-by-artist-wes-cockx-as-part-of-the-visuali.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    reactions: new Map([
      ['👍', 5],
      ['😂', 2],
    ]),
    self: false,
    sender: SENDER,
  },
  {
    id: '3',
    fileType: 'Audio',
    text: 'Here’s a voice message.',
    timeStamp: new Date(),
    file: 'audio1.mp3',
    self: true,
    sender: ME,
  },
  {
    id: '4',
    fileType: 'None',
    text: 'That’s awesome!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([
      ['❤️', 3],
      ['👍', 1],
    ]),
    self: false,
    sender: SENDER,
  },
  {
    id: '5',
    fileType: 'Video',
    text: 'Watch this video.',
    timeStamp: new Date(),
    file: 'https://videos.pexels.com/video-files/27798120/12227662_1080_1920_30fps.mp4',
    self: true,
    sender: ME,
  },
  {
    id: '6',
    fileType: 'None',
    text: 'What do you think?',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['😮', 1]]),
    self: false,
    sender: SENDER,
  },
  {
    id: '7',
    fileType: 'None',
    text: 'I love this!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['❤️', 4]]),
    self: true,
    sender: ME,
  },
  {
    id: '8',
    fileType: 'Image',
    text: 'Here’s another image.',
    timeStamp: new Date(),
    file: 'https://images.pexels.com/photos/12670543/pexels-photo-12670543.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    self: false,
    sender: SENDER,
  },
  {
    id: '9',
    fileType: 'None',
    text: 'Can you send me the file?',
    timeStamp: new Date(),
    file: '',
    self: true,
    sender: ME,
  },
  {
    id: '10',
    fileType: 'Audio',
    text: 'Here’s the audio file.',
    timeStamp: new Date(),
    file: 'audio2.mp3',
    self: false,
    sender: SENDER,
  },
  {
    id: '11',
    fileType: 'None',
    text: 'That was funny!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['😂', 3]]),
    self: true,
    sender: ME,
  },
  {
    id: '12',
    fileType: 'Video',
    text: 'Watch this video as well.',
    timeStamp: new Date(),
    file: 'https://videos.pexels.com/video-files/28351196/12365243_1080_1920_60fps.mp4',
    reactions: new Map([
      ['😮', 2],
      ['👍', 1],
    ]),
    self: false,
    sender: SENDER,
  },
  {
    id: '13',
    fileType: 'None',
    text: 'I’m excited!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['❤️', 2]]),
    self: true,
    sender: ME,
  },
  {
    id: '14',
    fileType: 'Image',
    text: 'Check this meme.',
    timeStamp: new Date(),
    file: 'https://images.pexels.com/photos/28410266/pexels-photo-28410266/free-photo-of-mavi-gol.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    self: false,
    sender: SENDER,
  },
  {
    id: '15',
    fileType: 'None',
    text: 'That’s hilarious!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['😂', 5]]),
    self: true,
    sender: ME,
  },
  {
    id: '16',
    fileType: 'Audio',
    text: 'Another audio for you.',
    timeStamp: new Date(),
    file: 'https://www.pagalworld.com.so/files/download/type/128/id/15530',
    self: false,
    sender: SENDER,
  },
  {
    id: '17',
    fileType: 'Video',
    timeStamp: new Date(),
    text: 'Watch this new clip.',
    file: 'https://videos.pexels.com/video-files/28351196/12365243_1080_1920_60fps.mp4',
    self: true,
    sender: ME,
  },
  {
    id: '18',
    fileType: 'Document',
    text: 'Here’s the PDF document.',
    timeStamp: new Date(),
    file: 'https://videos.pexels.com/video-files/28351196/12365243_1080_1920_60fps.mp4',
    self: false,
    sender: SENDER,
  },
  {
    id: '19',
    fileType: 'Document',
    text: 'This is my presentation.',
    timeStamp: new Date(),
    file: 'https://morth.nic.in/sites/default/files/dd12-13_0.pdf',
    self: true,
    sender: ME,
  },
  {
    id: '20',
    fileType: 'None',
    text: 'That’s interesting.',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['😮', 3]]),
    self: false,
    sender: SENDER,
  },
  {
    id: '21',
    fileType: 'None',
    text: 'This is getting exciting!',
    timeStamp: new Date(),
    file: '',
    reactions: new Map([['❤️', 5]]),
    self: true,
    sender: ME,
  },
  {
    id: '22',
    fileType: 'Image',
    text: 'Another cool picture!',
    timeStamp: new Date(),
    file: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/913cc6163828599.63ec999b44207.jpg',
    reactions: new Map([['👍', 3]]),
    self: false,
    sender: SENDER,
  },
];
